### ISSUE TITLE
UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions

### ISSUE THREAD

**Issue by eiyu** [Juby210/discord.js-reaction-menu#3]
when you clicking the reaction button it gives me 
```
UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
    at item.request.gen.end (/Users/yuliana/projects/inobase/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
    at then (/Users/yuliana/projects/inobase/node_modules/snekfetch/src/index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2251) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:2251) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2251) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
```

**Comment by Juby210** [comment]
Your bot doesn't has permissions to remove reaction

**Comment by eiyu** [comment]
ok thanks, it's in the dev portal

**Comment by Russian-Boy770** [comment]
> ok thanks, it's in the dev portal

Where in the dev portal?(I have the same error)
